#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.0a11_50bfd5f1a2f4"
#define UNITY_VERSION_FULL_NICE "2019.2.0a11 (50bfd5f1a2f4)"
#define UNITY_VERSION_BLD 5291989
#define UNITY_VERSION_DATE 1554211983
#define UNITY_VERSION_WIN "2019.2.0.5291989"
#define UNITY_VERSION_BRANCH "trunk"
